### PR TITLE
Add more string goodness

### PR DESCRIPTION
**Pull request by CJ-Wright**
Sorry I don't know why I didn't have this in the previous PR. The idea is that streams can have names for more descriptive power.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@mrocklin @ordirules ready for review.

**Comment by ordirules** [comment]
I don't have much opinions. I'm actually not familiar with the use cases of `str(foo)`. All I've used it for is for logging, in which case I'd agree. So I'm fine either way.

**Comment by mrocklin** [comment]
Same.  Merging.

Also, FWIW, I've been squash-merging on PRs with many commits that boil down to one objective.  Hope you're ok with this.

**Comment by CJ-Wright** [comment]
That's fine with me

**Comment by CJ-Wright** [comment]
There purpose of this is for the plotting if the graph which will use the string data in the node names

**Pull request merged**
